# Generated by Django 4.2.4 on 2023-09-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registered_Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=255)),
                ("registration_date", models.DateField(auto_now=True)),
                (
                    "user_image",
                    models.ImageField(
                        default="media/default.png", upload_to="media/user_media"
                    ),
                ),
            ],
        ),
    ]
