# Generated by Django 4.2.4 on 2023-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registered_users",
            name="registration_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
