# Generated by Django 4.2.4 on 2023-09-07 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_registered_users_registration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registered_users",
            options={"ordering": ["username"]},
        ),
        migrations.AddField(
            model_name="registered_users",
            name="last_login",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
